version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: echo "A first hello"
  test:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 5

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          # only run this job if 'build' succeeds
          requires:
            - build
