version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 5
  test_a:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 5
  test_b:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: echo "A localized hola"
      - run: sleep 5
  deploy:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: echo "a final goodbye"
      - run: sleep 5


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_a:
          requires:
            - build
      - test_b:
          requires:
            - build
      - deploy:
          requires:
            - test_a
            - test_b
