version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
  test_a:
    docker:
      - image: circleci/node:6
    steps:
      - attach_workspace:
          at: my_workspace
      - run: cat my_workspace/echo-output
  test_b:
    docker:
      - image: circleci/node:6
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_workspace
      - run: |
          # this will fail intentionally, we'll use SSH to debug and fix
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
  deploy:
    docker:
      - image: circleci/node:6
    steps:
      - attach_workspace:
          at: my_workspace
      - run: |
          echo "Deploying message!"
          cat my_workspace/echo-output

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_a:
          requires:
            - build
      - test_b:
          requires:
            - build
      - deploy:
          requires:
            - test_a
            - test_b
